Repository grapl-security/grapl, pull requests merged in 2022-10, with the labels that each got.

#2060 Fix s3 uri format so that its explicitly a s3 URI
  src/rust/plugin-registry/src/server/deploy_plugin.rs
  src/rust/plugin-registry/src/server/mod.rs
  src/rust/plugin-registry/src/server/s3_uri.rs
  src/rust/plugin-registry/src/server/s3_url.rs
Labels: bug

#2037 Scylla optimize provision
  src/rust/Cargo.lock
  src/rust/graph-mutation/Cargo.toml
  src/rust/graph-mutation/src/graph_mutation.rs
  src/rust/graph-query/Cargo.toml
  src/rust/graph-query/src/property_query.rs
  src/rust/scylla-provisioner/Cargo.toml
  src/rust/scylla-provisioner/src/server.rs
  src/rust/scylla-provisioner/src/table_names.rs
Labels: Stale

#2076 Chore: Upgrade Nomad to 1.4.1 and Consul to 1.12.6
  etc/chromeos/lib/installs.sh
Labels: chore

#2083 Chore: Upgrade otel-collector
  nomad/observability.nomad
Labels: chore

#2084 Set service.version on the service level
  nomad/grapl-core.nomad
  nomad/grapl-graph-db.nomad
  nomad/grapl-provision.nomad
  nomad/local/python-integration-tests.nomad
  nomad/rust-integration-tests.nomad
  pulumi/grapl/__main__.py
  pulumi/infra/docker_images.py
  pulumi/python_integration_tests/__main__.py
  pulumi/rust_integration_tests/__main__.py
Labels: bug

#2086 Format BUILD files with black
  BUILD
  devbox/BUILD
  devbox/provision/BUILD
  devbox/provision/infra/BUILD
  docker-plugin-runtime/BUILD
  etc/hooks/BUILD
  firecracker/cni/BUILD
  firecracker/kernel/BUILD
  firecracker/rootfs/BUILD
  pants.toml
  pulumi/hcl2_type_reflection/BUILD
  pulumi/hcl2_type_reflection/hcl2_type_reflection/BUILD
  scylladb/BUILD
  src/python/grapl-plugin-sdk/example_analyzers/BUILD
  src/python/grapl-plugin-sdk/grapl_plugin_sdk/analyzer/BUILD
  src/python/python-proto/python_proto/tests/BUILD
  src/sh/BUILD
Labels: chore
